trigger:
- master
  
pool:
  vmImage: ubuntu-latest
stages:
  - stage: Build  
    jobs:
    - job: Build
      steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.9'
        displayName: 'Use Python 3.9'
    
      - script: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements-build.txt 
        displayName: 'Install dependencies for build'
        workingDirectory: $(System.DefaultWorkingDirectory)
  
  - stage: Test
    jobs:
    - job: Test
      steps:
      - script: |
          source venv/bin/activate
          pytest test_python_calculator.py
        displayName: 'Unit tests'
        workingDirectory: $(System.DefaultWorkingDirectory)/test/