trigger:
- master
  
pool:
  vmImage: ubuntu-latest
  
  strategy:
    matrix:
      python39:
        python.version: '3.9'
  
stages:
  - stage: Build 
    jobs:
    - job: 
      steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.version)'
        displayName: 'Use Python $(python.version)'
    
      - script: |
          pip install -r requirements-build.txt
        displayName: 'Install dependencies for build'
        workingDirectory: $(System.DefaultWorkingDirectory)
  
  - stage: Integration_Test
    jobs:    
    - job:
      dependsOn: Build
      steps:
      - script: |
          pytest test_python_calculator.py
        displayName: 'Unit tests'
        workingDirectory: $(System.DefaultWorkingDirectory)/test/
    

    
    
