trigger:
- master

parameters:
  - name: run_test
    type: boolean
    default: true

pool:
  vmImage: ubuntu-latest

stages:
- stage: build
  jobs:
  - job: build_job
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.9'
        displayName: 'Use Python 3.9'
        
      - script: |
          sudo apt-get update
          python3 -m venv venv
          source ./venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements-build.txt 
        displayName: 'Install dependencies for build'
        workingDirectory: $(System.DefaultWorkingDirectory)
      
      - script: |
          python setup.py dist
        displayName: 'Build Python Distribution'
        workingDirectory: $(System.DefaultWorkingDirectory)

      # run python tests
      - script: |
          pip install pytest
          python setup.py test
        displayName: 'All unit tests'
        condition: and(succeeded(), eq(${{ parameters.run_test }}, true))
        failOnStderr: false

  - job: artifacts
    steps:
    - script: |
        pip install wheel setuptools
        python setup.py sdist bdist_wheel
        ls dist
      displayName: 'Build Python Distribution'

    - task: PublishBuildArtifacts@1
      condition: succeeded()
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)/dist'
        ArtifactName: 'python-artifact'
      
  

