trigger:
- master
  
pool:
  vmImage: ubuntu-latest
  
  strategy:
    matrix:
      python39:
        python.version: '3.9'
  
stages:
  - stage: BuildAndTest 
    jobs:
    
    - job: PythonVersion
      steps:
        - script: echo 'Setting python $(python.version)'
          env:
            python.version: $(python.version)

    - job: Build
      steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.version)'
        displayName: 'Use Python $(python.version)'
    
      - script: |
          pip install -r requirements-build.txt
        displayName: 'Install dependencies for build'
        workingDirectory: $(System.DefaultWorkingDirectory)
  
  
    - job: Test
      dependsOn: Build
      steps:
      - script: |
          echo "Running integration tests"

    - job:
      steps:
      - script: |
          pytest test_python_calculator.py
        displayName: 'Unit tests'
        workingDirectory: $(System.DefaultWorkingDirectory)/test/