trigger:
- master

parameters:
  - name: run_test
    type: boolean
    default: true

stages:
- stage: build
  jobs:
  - job: build_job
  pool:
    vmImage: ubuntu-latest
  
    steps:
    - template: build_python.yml
      parameters:
        run_test: ${{ parameters.run_test}}


- stage: deploy_dev
  jobs:
  - job: deploy_job
  

