trigger:
- master

pool:
  vmImage: ubuntu-latest

strategy:
  matrix:
    python39:
      python.version: '3.9'
    
steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'

  - script: |
      python -m pip install --upgrade pip
      pip install pytest pytest-azurepipelines
      pytest test_python_calculator.py
    displayName: 'pytest'
    workingDirectory: $(System.DefaultWorkingDirectory)/test/


      
    
