trigger:
- master

pool:
  vmImage: ubuntu-latest

strategy:
  matrix:
    python39:
      python.version: '3.9'
    
jobs:
- job: 'requirements and dependencies'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      displayName: 'Use Python $(python.version)'

    - script: |
        pip install -r requirements-build.txt
        displayName: 'Install dependencies for build'
      workingDirectory: $(System.DefaultWorkingDirectory)

- job: 'Integration tests'
  dependsOn: 'requirements and dependencies'
  -script: |
    pytest test_python_calculator.py
  workingDirectory: $(System.DefaultWorkingDirectory)/test/

      
    
