trigger:
- master

parameters:
  - name: run_test
    type: boolean
    default: true

pool:
  vmImage: ubuntu-latest

stages:
- stage: build
  jobs:
  - job: build_job
    steps:

      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.9'
        displayName: 'Use Python 3.9'
        
      - script: |
          sudo apt-get update
          
          python -m pip install --upgrade pip
          pip install -r requirements-build.txt 
        displayName: 'Install dependencies for build'
        workingDirectory: $(System.DefaultWorkingDirectory)

      # run python tests
      - script: |
          pip install pytest
          pytest 
        displayName: 'All unit tests'
        workingDirectory: $(System.DefaultWorkingDirectory)/test/

- stage: PublishArtifact
  jobs:
  - job: Publish
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.9'
      displayName: 'Use Python 3.9'

    - script: |
        pip install wheel setuptools
        python setup.py sdist bdist_wheel
      displayName: 'Build Python Distribution'

    - task: PublishBuildArtifacts@1
      condition: succeeded()
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)/dist'
        ArtifactName: 'python-artifact'
      
  

