parameters:
  name: run_test
  type: boolean
  default: true

pool:
  vmImage: ubuntu-latest
stages:
  - stage: Build  
    jobs:
    - job: Build
      steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.9'
        displayName: 'Use Python 3.9'
        
      - script: |
          sudo apt-get update
          
          python -m pip install --upgrade pip
          pip install -r requirements-build.txt 
        displayName: 'Install dependencies for build'
        workingDirectory: $(System.DefaultWorkingDirectory)

      # run python tests
      - script: |
          pip install pytest
          pytest 
        displayName: 'All unit tests'
        condition: and(succeeded(), eq(${{ parameters.run_test }}, true))
        failOnStderr: false
  
    - job: Test
      steps:
      - script: |
          pip install pytest
          pytest 
        displayName: 'Unit tests'
        workingDirectory: $(System.DefaultWorkingDirectory)/test/

        